on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  

name: etinho

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    - name: Aplication dependency
      run:  echo usuario logado com sucesso

    - name: Aplication build
      run:  docker run build -t etinho .

    - name: etapa de teste 
      run:  echo teste com 100% com sucesso

    - name: final
      run: echo deploy success