on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  

name: etinho

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: usuario logado
      run:  echo você está logado

    - name: Aplication dependency
      run:  docker run build -t etinho .

    - name: Final
      run: echo parabéns você fez o deploy com sucesso